<?php
	use LogmUser;

	class DplusUser extends WireData implements Module {
		public static function getModuleInfo() {
			return array(
				'title' => 'Dplus User Extension',
				'version' => 102,
				'summary' => 'Extends $user object with dplus methods',
				'singular' => true,
				'autoload' => true,
			);
		}

		public function init() {
			$this->addHook('User::is_admin', $this, 'is_admin');
			$this->addHook('User::is_salesmanager', $this, 'is_salesmanager');
			$this->addHookProperty('User::dpluso_role', function($event) {
				$user = $event->object;
				$logmuser = LogmUser::load($user->name);
				$event->return = $logmuser ? wire('config')->user_roles[$logmuser->get_dplusorole()]['label'] : 'Not Found';
			});
		}

		public function is_admin($event) {
			$user = $event->data['object'];
			$event->return = $user->hasRole($this->wire('config')->user_roles['admin']['dplus-code']);
		}

		public function is_salesmanager($event) {
			$user = $event->data['object'];
			$event->return = $user->hasRole($this->wire('config')->user_roles['sales-manager']['dplus-code']);
		}
	}
?>
